# Business Configuration
# This file contains all business-specific configuration for the website
# It's safe to commit this file to version control as it contains no sensitive data

# =====================================================
# BUSINESS INFORMATION
# =====================================================
business:
  name: Melbourne Roof Cleaning Pros
  logo: /images/Melbourne-Roof-Cleaning-Pros-logo.png
  tagline: Professional roof washing service to restore your roof's appearance and extend its lifespan
  phone: "(03) 4514 5137"
  email: info@melbourneroofcleaningpros.com.au
  owner_name: Phil Harry
  broad_region: Greater Melbourne
  form_location: Hampton

# =====================================================
# BUSINESS ADDRESS
# =====================================================
address:
  street: "2/19 Chandos St"
  city: Cheltenham
  state: VIC
  postcode: "3192"
  country: Australia

# =====================================================
# SERVICE CONFIGURATION
# =====================================================
service:
  main_category: Roof Cleaning
  main_location: Melbourne
  radius_km: 35
  max_location_pages: 800
  # Melbourne CBD coordinates
  center_lat: -37.8136
  center_lng: 144.9631 

# =====================================================
# BRAND COLORS
# =====================================================
# Colors should be hex values without the # prefix
colors:
  primary: "004AAB"    # Professional blue
  secondary: "059669"  # Green (eco-friendly)
  accent: FF5E01     # Orange accent
  cta: DB4F01       # Orange CTA buttons

# =====================================================
# BUSINESS HOURS
# =====================================================
hours:
  monday: 7:00 AM - 7:00 PM
  tuesday: 7:00 AM - 7:00 PM
  wednesday: 7:00 AM - 7:00 PM
  thursday: 7:00 AM - 7:00 PM
  friday: 7:00 AM - 7:00 PM
  saturday: 7:00 AM - 7:00 PM
  sunday: 7:00 AM - 7:00 PM

# =====================================================
# SOCIAL MEDIA
# =====================================================
social:
  facebook: https://www.facebook.com/MelbourneRoofCleaningPros
  instagram: ""
  linkedin: ""
  youtube: ""

# =====================================================
# WEBSITE & SEO
# =====================================================
website:
  url: https://www.melbourneroofcleaningpros.com.au
  google_maps_url: ""
  google_reviews_url: ""

# =====================================================
# GOOGLE MAPS INTEGRATION
# =====================================================
google_maps:
  # Full iframe embed code from Google Maps (enclose in quotes)
  embed: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6291.736094222842!2d145.0412595!3d-37.9568669!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad66e9a497ad487%3A0xd332431aaaecac36!2s2%2F19%20Chandos%20St%2C%20Cheltenham%20VIC%203192!5e0!3m2!1sen!2sau!4v1758512249151!5m2!1sen!2sau" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'

# =====================================================
# FOOTER CONFIGURATION
# =====================================================
footer:
  # Featured suburbs to display in the footer (max 11)
  # Leave empty [] for automatic smart selection based on population and distance
  # Or specify suburb names manually like ["Parramatta", "Bondi", "Manly"]
  featured_suburbs: [
    "Hawthorn",
    "Camberwell",
    "Kew",
    "Balwyn",
    "Glen Iris",
    "Brighton",
    "Sandringham",
    "Hampton",
    "Bentleigh",
    "Toorak",
    "Malvern",
    "Armadale",
    "Glen Waverley",
    "St Kilda"
  ]

  # Selection mode for handling multiple suburb matches
  # Options: 'best_match' (default) or 'all_variations'
  suburb_selection_mode: best_match

  # Auto-supplement with smart selection if fewer than 11 suburbs
  # Set to false to show only explicitly listed suburbs
  auto_supplement: false

  # Maximum number of suburbs to display (optional)
  # Leave unset to show all featured suburbs
  # suburb_limit: 15